### ISSUE TITLE
Default output of fitCor is massive

### ISSUE THREAD

**Issue by morrowcj** [morrowcj/remotePARTS#11]
## UPDATE

See comments below 

----

#### Problem

Because I elected to save the fitted `nls` object (as `$mod`) in the output of `fitCor`, the results can be quite large. I was unaware of how big `nls` objects are. 

#### Solution

The solution is to add a `save_mod` argument to `fitCor()`. Setting it to `FALSE` will save tons of memeory for large datasets.

**Comment by morrowcj** [comment]
Even with `save_mod = FALSE`, `fitCor()` is failing because it fails to allocate an enormous vector:
```R
fitCor(resids = temporal_residuals, coords = as.matrix(data_raw[, coord_cols]),
       distm_FUN = "distm_km", start = list(r = 1000), fit.n = cor_fit_n, save_mod = FALSE)
```
```R
 Error: cannot allocate vector of size 62347.8 Gb 
```

even though the data is not particularly large:
```R
> format(object.size(data_raw), units = "MB")
[1] "275.9 Mb"

> format(object.size(temporal_residuals), units = "MB")
[1] "441.4 Mb"
```

This has to be an actual bug.

**Comment by arives** [comment]
I think the solution of using the subsampled data to estimate the max dist is reasonable. Maybe having fitCor() return that maximum distance it uses would be useful in case anybody wants to make the small adjustment in parameter values if the “true” max dist is known.


From: Clay Morrow ***@***.***>
Date: Friday, December 16, 2022 at 12:05 AM
To: morrowcj/remotePARTS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [morrowcj/remotePARTS] Default output of fitCor is massive (Issue #11)
Problem

I believe I've found the problem. Lines 142-147 of R/fitCor.R fits a distance matrix to the full dataset. Which is impossible for very large datasets. I have no idea what I was thinking.

Solution?

Obviously, we need to remove this line. It exists only to get the maximum distance between two points on the map so that it can be used to rescale the spatial parameters. Perhaps it is simply enough to use an estimate of the max distance of the full dataset by actually calculating the max distance between the sampled points (as determined by fit.n).

**Comment by morrowcj** [comment]
Tony,

I think I found a better (and very fast) solution. Would you mind reviewing my code though? You can do so in a browser by looking at the changes I made here: https://github.com/morrowcj/remotePARTS/pull/16/files

It shouldn’t take much time at all, since I only changed 71 lines of code. If you do notice anything that needs to be changed or clarified, please let me know. An easy way would be with the green “Review changes” button in the top right. If the code looks good, selecting “approve” under the review drop-down would be greatly appreciated.

Thank you,
-Clay
