### ISSUE TITLE
Variance instead of SE

### ISSUE THREAD

**Issue by morrowcj** [morrowcj/remotePARTS#2]
In `fitAR`, the returned values of `SE` are, in fact, variances. 

* [x] The code should be something like `SE = diag(s2beta)^0.5`
* [x] check if other versions of fitX have this problem.

**Comment by Rapsodia86** [comment]
Hi, 
any plans to have it updated?

**Comment by arives** [comment]
Monika,

Yep, Clay is just about to. Everything else, including the t-scores and p-values, is fine; it’s really just a matter of taking the square-root of the printed SEs for the fitAR and fitCLS functions.

Sorry about this, Tony

__________________________
Anthony R. Ives (he/him/his)
UW-Madison
459 Birge Hall
608-262-1519


From: Monika Anna Tomaszewska ***@***.***>
Date: Monday, November 14, 2022 at 3:42 PM
To: morrowcj/remotePARTS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [morrowcj/remotePARTS] Variance instead of SE (Issue #2)

Hi,
any plans to have it updated?

**Comment by Rapsodia86** [comment]
Hello,
Thanks for the quick answer!
Yes, I have explored the code to find where to apply the correction (or to be aware about the output).
But I appreciate the fact you are going to do this! Thanks!

**Comment by morrowcj** [comment]
@Rapsodia86 and @arives, 

I just wanted to alert you that I've corrected this (with PR #4) and will be merged into the live branch as soon as the build checks finish running. Sorry it took so long to get to this simple fix!

Having addressed the problem, I'm closing this issue now.

**Comment by Rapsodia86** [comment]
Thank you for the update and fixing the issue!
